# Necessary information, if you don't know, just leave it alone
Icon: Source/Image/Icon.png
TodoFile: Source/Text/Todo.txt
TodoArchive: Source/Text/TodoArchive.txt
TodoUIUpdateTime: 100

# Large language model, you can config the model used based on the following
LLM: ernie # ernie, glm3, GRADIO, WITHOUT
ErnieToken: 88ea362d6879c26099c527ebcf7fa601817ca10b # when LLM is ernie, use this token
GLM3Directory: Source/Model/chatglm3-6b-ov # when LLM is glm3, use this directory
GradioURL: http://116.62.10.217:8890/ # when LLM is GRADIO, use this URL

# DesktopPet(Physical) config
DesktopPet: 1 # whether to load DesktopPet, 1 for yes, 0 for no
