Icon: Source/Image/Icon.png
TodoFile: Source/Text/Todo.txt
LLM: glm3 # ernie, glm3, GRADIO, WITHOUT
ErnieToken: dfasfasfasdfsadfsadfsadfdfsad
GLM3Directory: Source/Model/chatglm3-6b-ov
GradioURL: http://116.62.10.217:8890/
TodoUIUpdateTime: 100