Icon: Source/Image/tigerIcon.jpg
Dialog: Source/Text/dialog.txt
ErnieToken: 1111111111111111111111111111
UserName: Master
AgentName: Pikachu
ImageChangeTime: 300000 # 300000ms = 5min
TalkChangeTime: 60000 # 60000ms = 1min
Image_size:
  - 200 # width
  - 200 # height
Images:
  Hang: Source/Image/main/hang.gif
  Normal:
    - Source/Image/main/normal1.gif
    - Source/Image/main/normal2.gif
    - Source/Image/main/normal3.gif