Icon: Source/Image/tigerIcon.jpg
Dialog: Source/Text/dialog.txt
ErnieToken: 88ea362d6879c26099c527ebcf7fa601817ca10b
UserName: Master
AgentName: Pikachu
Image_size:
  - 200 # width
  - 200 # height
Images:
  Hang: Source/Image/main/hang.gif
  Normal:
    - Source/Image/main/normal1.gif
    - Source/Image/main/normal2.gif
    - Source/Image/main/normal3.gif